/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Organizations;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationsRecord extends UpdatableRecordImpl<OrganizationsRecord> implements Record3<String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.organizations.name</code>.
     */
    public OrganizationsRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.organizations.inn</code>.
     */
    public OrganizationsRecord setInn(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.inn</code>.
     */
    public Long getInn() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.organizations.account</code>.
     */
    public OrganizationsRecord setAccount(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.account</code>.
     */
    public Long getAccount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Organizations.ORGANIZATIONS.NAME;
    }

    @Override
    public Field<Long> field2() {
        return Organizations.ORGANIZATIONS.INN;
    }

    @Override
    public Field<Long> field3() {
        return Organizations.ORGANIZATIONS.ACCOUNT;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Long component2() {
        return getInn();
    }

    @Override
    public Long component3() {
        return getAccount();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Long value2() {
        return getInn();
    }

    @Override
    public Long value3() {
        return getAccount();
    }

    @Override
    public OrganizationsRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public OrganizationsRecord value2(Long value) {
        setInn(value);
        return this;
    }

    @Override
    public OrganizationsRecord value3(Long value) {
        setAccount(value);
        return this;
    }

    @Override
    public OrganizationsRecord values(String value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationsRecord
     */
    public OrganizationsRecord() {
        super(Organizations.ORGANIZATIONS);
    }

    /**
     * Create a detached, initialised OrganizationsRecord
     */
    public OrganizationsRecord(String name, Long inn, Long account) {
        super(Organizations.ORGANIZATIONS);

        setName(name);
        setInn(inn);
        setAccount(account);
    }
}
