/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.InvoicesRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoices extends TableImpl<InvoicesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.invoices</code>
     */
    public static final Invoices INVOICES = new Invoices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoicesRecord> getRecordType() {
        return InvoicesRecord.class;
    }

    /**
     * The column <code>public.invoices.number</code>.
     */
    public final TableField<InvoicesRecord, Long> NUMBER = createField(DSL.name("number"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.invoices.date_of</code>.
     */
    public final TableField<InvoicesRecord, Date> DATE_OF = createField(DSL.name("date_of"), SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.invoices.organization_id</code>.
     */
    public final TableField<InvoicesRecord, Long> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Invoices(Name alias, Table<InvoicesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Invoices(Name alias, Table<InvoicesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.invoices</code> table reference
     */
    public Invoices(String alias) {
        this(DSL.name(alias), INVOICES);
    }

    /**
     * Create an aliased <code>public.invoices</code> table reference
     */
    public Invoices(Name alias) {
        this(alias, INVOICES);
    }

    /**
     * Create a <code>public.invoices</code> table reference
     */
    public Invoices() {
        this(DSL.name("invoices"), null);
    }

    public <O extends Record> Invoices(Table<O> child, ForeignKey<O, InvoicesRecord> key) {
        super(child, key, INVOICES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<InvoicesRecord> getPrimaryKey() {
        return Keys.INVOICE_PK;
    }

    @Override
    public List<UniqueKey<InvoicesRecord>> getKeys() {
        return Arrays.<UniqueKey<InvoicesRecord>>asList(Keys.INVOICE_PK);
    }

    @Override
    public Invoices as(String alias) {
        return new Invoices(DSL.name(alias), this);
    }

    @Override
    public Invoices as(Name alias) {
        return new Invoices(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoices rename(String name) {
        return new Invoices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoices rename(Name name) {
        return new Invoices(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Date, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
