/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Invoices;
import db.tables.Nomenclatures;
import db.tables.Organizations;
import db.tables.Positions;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.invoices</code>.
     */
    public static final Invoices INVOICES = Invoices.INVOICES;

    /**
     * The table <code>public.nomenclatures</code>.
     */
    public static final Nomenclatures NOMENCLATURES = Nomenclatures.NOMENCLATURES;

    /**
     * The table <code>public.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.positions</code>.
     */
    public static final Positions POSITIONS = Positions.POSITIONS;
}
